### ISSUE TITLE
DynamoDB Example/Template

### ISSUE THREAD

**Issue by trevorallred** [goldstack/goldstack#172]
Do you have any examples or resources for creating DynamoDB?

Would we need to extend the serverless-api Terraform scripts?

**Comment by mxro** [comment]
Adding a template based on DynamoDB is next on the list, see https://github.com/goldstack/goldstack/issues/12 for thoughts so far. Would be great if you could add there any specific requirements you have.

One thing I am not so sure about is how migrations would work. I think there are some node libraries to help with that but they look like they are not maintained, e.g. https://www.npmjs.com/package/dynamodb-migrations

Otherwise you could also just add a DynamoDB table to the Terraform files for the serverless-api package for now!

**Comment by mxro** [comment]
DynamoDB Template implemented and released at: https://goldstack.party/templates/dynamodb

Here a link directly to the source code for an example project: https://github.com/goldstack/dynamodb-boilerplate/tree/master/packages/dynamodb-1/src

Any feedback welcome 😊

**Comment by mxro** [comment]
Closing this issue now - for any feedback or further ideas for the DynamoDB template, please reach out!
